name: "Branch Manager"
description: "Automatically copy content between repository branches"
author: "Tufts University"

inputs:
  source-branch:
    required: false
    default: ${{ github.ref_name }}
  destination-branch:
    required: true
  clear-destination:
    required: false
    default: "false"
  copy:
    required: false
    default: ""
  replace:
    required: false
    default: ""

runs:
  using: composite
  steps:
    - id: allow-execution
      run: chmod +x ${{ github.action_path }}/*.sh
      shell: bash
    - id: checkout-source
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.source-branch }}
        path: repo
    - id: stage-files
      run: ${{ github.action_path }}/stage-files.sh
      shell: bash
      env:
        REPO: repo
        STAGING: staging
        INPUTS_COPY: ${{ inputs.copy }}
    - id: replace-strings
      run: ${{ github.action_path }}/replace-strings.sh
      shell: bash
      env:
        STAGING: staging
        INPUTS_REPLACE: ${{ inputs.replace }}
    - id: push-changes
      run: ${{ github.action_path }}/push-changes.sh
      shell: bash
      env:
        REPO: repo
        BRANCH: ${{ inputs.destination-branch }}
        CLEAR: ${{ inputs.clear-destination }}
        STAGING: staging
        MESSAGE: ${{ github.sha }}
